### PR TITLE
CMP 2.4 hotfix changes

### PR DESCRIPTION
**Pull request by v-saikirang**

### CODE REVIEW

**Comment by v-saikirang** [comment]
@microsoft-github-policy-service agree [company="LTIMindtree"]

**Comment by v-saikirang** [comment]
@microsoft-github-policy-service agree

**Comment by v-saikirang** [comment]
@JoshLeporati Pushing changes for CMP 2.4 hotfix for the bug related to the version format. Please review.

**Review by JoshLeporati — APPROVED** [review]
approved, thank you!

**Pull request merged**
